- name: Update Jira Issue
  uses: atlassian/gajira-comment@v2
  with:
    issue: PROJECT-101
    body: "Build successful and merged into main. Release v1.0.0 includes this change."
  env:
    JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
    JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
